# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false 


submodules:
  exclude: all

python:
  version: 3.7
  install:
    - requirements: docs/source/requirements.txt
