sudo: false
dist: bionic
language: c++ 

compiler: 
  - gcc

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - cmake
    - libelf-dev 
    - ninja-build

cache:
  directories:
    - TEMP

  env:
  - BUILD=RELEASE 
  - TARGET_ARCH=linux64 
  - SYSTEMC=systemc-2.3.3
  - CXX=clang++

    # systemc compilation 
    # credit: https://github.com/janweinstock/vcml/blob/master/.travis.yml
install:
  - mkdir -p DEPENDS && cd DEPENDS
  - export SYSTEMC=systemc-2.3.3; export TARGET_ARCH=linux64; export BUILD=RELEASE
  - export SYSTEMC_HOME=`pwd`/$SYSTEMC
  - echo $SYSTEMC_HOME
  - echo $LLVM_LD_FLAGS
  - | # Build SystemC
      if [ ! -d $SYSTEMC_HOME ]; then
          wget https://www.accellera.org/images/downloads/standards/systemc/$SYSTEMC.tar.gz
          tar -xzf $SYSTEMC.tar.gz && cd $SYSTEMC
          mkdir BUILD && cd BUILD
          ../configure --enable-static CXXFLAGS="-std=c++14"
          make -j 4 && make install
          cd ../..
          rm -rf $SYSTEMC.tar.gz $SYSTEMC/BUILD
      fi
  - cd ..
  - | # Build clang 
    cd DEPENDS
    wget https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    tar xf clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz 
    mv clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04 clang-7.0.0

    # Debug
    # Setup flags
    export LLVM_INSTALL_DIR=`pwd`/clang-7.0.0
    export LLVMCONFIG=$LLVM_INSTALL_DIR/bin/llvm-config
    export LLVM_LD_FLAGS=-L$LLVM_INSTALL_DIR/lib
    export LLVM_CXX_FLAGS="-I/home/travis/build/rseac/systemc-clang/DEPENDS/clang-7.0.0/include  -fPIC -fvisibility-inlines-hidden -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -fno-rtti -D_GNU_SOURCE -fvisibility-inlines-hidden -Wsign-compare"
    export LLVM_LIBS="-lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser -lLLVMFuzzMutate -lLLVMCoverage -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMWindowsManifest -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMBitWriter -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle"
    cd ..


before_script:
  #  - mkdir BUILD && cd BUILD
  # - cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  - export SYSTEMC=$SYSTEMC_HOME/
  - export CC=$LLVM_INSTALL_DIR/bin/clang
  - export CXX=$LLVM_INSTALL_DIR/bin/clang++
  - echo $CXX
  - mkdir -p TEMP; cd TEMP;
  - cmake ../ -DCMAKE_VERBOSE_MAKEFILE=on && make
    #- cmake ../ -DCMAKE_VERBOSE_MAKEFILE=on && make
  - cd ..; rm -rf TEMP
